// <auto-generated />
namespace DarehService.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class useru : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useru));
        
        string IMigrationMetadata.Id
        {
            get { return "201606020916281_user-u"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
